# Triggers after the "Downstream artifacts" build has finished, to run the
# matrix-react-sdk playwright tests (with access to repo secrets)

name: matrix-react-sdk End to End Tests
on:
    merge_group:
        types: [checks_requested]

    pull_request: {}

    # For now at least, we don't run this or the downstream-end-to-end-tests against pushes
    # to develop or master.
    #
    #push:
    #    branches: [develop, master]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch || github.run_id }}
    cancel-in-progress: ${{ github.event.workflow_run.event == 'pull_request' }}

jobs:
    playwright:
        name: Playwright
        uses: matrix-org/matrix-react-sdk/.github/workflows/end-to-end-tests.yaml@develop
        permissions:
            actions: read
            issues: read
            pull-requests: read
        with:
            matrix-js-sdk-sha: ${{ github.sha }}
            react-sdk-repository: matrix-org/matrix-react-sdk
            # We only want to run the playwright tests on merge queue to prevent regressions
            # from creeping in. They take a long time to run and consume multiple concurrent runners.
            skip: ${{ github.event_name != 'merge_group' }}
