name: Release Process
on:
  release:
    types: [ published ]
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  jsdoc:
    name: Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§® Checkout code
        uses: actions/checkout@v3

      - name: ğŸ”§ Yarn cache
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - name: ğŸ”¨ Install dependencies
        run: "yarn install --pure-lockfile"

      - name: ğŸ“– Generate JSDoc
        run: "yarn gendoc"

      - name: ğŸ§® Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh_pages

      - name: ğŸ“‹ Copy to gh-pages
        run: |
          # Copy into the folder structure
          tag="${{ github.ref_name }}"
          version="${tag#v}"
          ls -lah
          cp -a "./.jsdoc/matrix-js-sdk/$version" ./gh_pages/

          # Add the new directory to the index if it isn't there already
          if ! grep -q "Version $version" gh_pages/index.html; then
            perl -i -pe 'BEGIN {$rel=shift} $_ =~ /^<\/ul>/ && print
              "<li><a href=\"${rel}/index.html\">Version ${rel}</a></li>\n"' "$version" gh_pages/index.html
          fi

      - name: ğŸŒ Deploy to Github Pages
        working-directory: gh_pages
        run: |
          git add --all .
          git commit --no-verify -am "Add jsdoc for ${{ github.ref_name }}"
          git push origin gh-pages
