name: Notify Downstream Projects
on:
  push:
    branches: [ develop, t3chguy/ci1 ]
jobs:
  notify-matrix-react-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Notify matrix-react-sdk repo that a new SDK build is on develop so it can CI against it
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ELEMENT_BOT_TOKEN }}
          repository: vector-im/element-web
          event-type: element-web-notify
