# Find details about the PR associated with this ref
# Outputs:
#  prnumber: the ID number of the associated PR
#  headref: the name of the head branch of the PR
#  baseref: the name of the base branch of the PR
name: PR Details
on:
  workflow_call:
    inputs:
      owner:
        type: string
        required: true
        description: The github username of the owner of the head branch
      branch:
        type: string
        required: true
        description: The name of the head branch
    outputs:
      pr_id:
        description: The ID of the PR found
        value: ${{ jobs.prdetails.outputs.pr_id }}
      head_branch:
        description: The head branch of the PR found
        value: ${{ jobs.prdetails.outputs.head_branch }}
      base_branch:
        description: The base branch of the PR found
        value: ${{ jobs.prdetails.outputs.base_branch }}
      labels:
        description: JSON array of labels which the PR has
        value: fromJSON{{ jobs.prdetails.outputs.labels }})

jobs:
  prdetails:
    name: Find PR Details
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ” Read PR details"
        id: details
        uses: actions/github-script@v5
        with:
          # We need to find the PR number that corresponds to the branch, which we do by searching the GH API
          # The workflow_run event includes a list of pull requests, but it doesn't get populated for
          # forked PRs: https://docs.github.com/en/rest/reference/checks#create-a-check-run
          script: |
            const [owner, repo] = "${{ github.action_repository }}".split("/");
            const pulls = await github.rest.pulls.list({
              head: "${{ inputs.owner }}:${{ inputs.branch }}",
              owner,
              repo,
            });
            const pr = pulls[0];
            if (pr) {
              console.log("::set-output name=prnumber::" + pr.number);
              console.log("::set-output name=headref::" + pr.head.ref);
              console.log("::set-output name=baseref::" + pr.base.ref);
              console.log("::set-output name=labels::" + JSON.stringify(pr.labels.map(l => l.name)));
            }
    outputs:
      pr_id: ${{ steps.details.outputs.prnumber }}
      head_branch: ${{ steps.details.outputs.headref }}
      base_branch: ${{ steps.details.outputs.baseref }}
      labels: ${{ steps.details.outputs.labels }}
